import { baseScale } from '../common.js';

export const wellsDvt = baseScale({
  id: 'wells-dvt',
  name: 'Wells DVT Score',
  nameEn: 'Wells DVT Score',
  category: 'pretest',
  categoryLabel: 'VTE 验前概率',
  description: '评估深静脉血栓（DVT）的临床验前概率，用于分层后续检查策略。',
  scenario: '疑似下肢深静脉血栓的门诊或急诊患者',
  reference: 'Wells PS et al. Lancet 1997',
  year: '1997',
  type: 'additive',
  estimatedItems: 10,
  formulaNote: '总分 = 各阳性项分值之和；「其他诊断可能性≥DVT」为 -2 分（医护判断项）。',
  items: [
    {
      id: 'wells-dvt.cancer',
      clinicalLabel: '活动性癌症（近6个月接受治疗或姑息治疗）',
      patientPrompt: '过去6个月内，您是否因癌症接受过治疗（包括化疗、放疗或姑息治疗）？',
      helpText: '如不确定，请咨询主治医生。',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.paralysis',
      clinicalLabel: '瘫痪、轻瘫或近期下肢石膏固定',
      patientPrompt: '您是否有瘫痪、轻瘫，或近期下肢打了石膏固定？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.bedridden',
      clinicalLabel: '近期卧床≥3天或近4周内大手术',
      patientPrompt: '您是否近期卧床至少3天，或在过去4周内做过较大的手术？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.tenderness',
      clinicalLabel: '沿深静脉走行的局部压痛',
      patientPrompt: '医生检查时，沿您下肢深静脉走行处是否有明显压痛？',
      helpText: '此项通常由医护人员查体确认。',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.swelling',
      clinicalLabel: '整个下肢肿胀',
      patientPrompt: '您是否感觉整条下肢明显肿胀？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.calf',
      clinicalLabel: '小腿肿胀>3cm（较无症状侧）',
      patientPrompt: '与另一侧相比，有症状的小腿是否肿胀超过约3厘米？',
      helpText: '常由医护人员测量对比。',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.edema',
      clinicalLabel: '凹陷性水肿（有症状侧）',
      patientPrompt: '有症状的那侧下肢按压后是否出现凹陷性水肿？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.collateral',
      clinicalLabel: '浅静脉侧支循环（非静脉曲张性）',
      patientPrompt: '医生是否发现您下肢有非静脉曲张性的浅静脉侧支扩张？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.history',
      clinicalLabel: 'DVT病史',
      patientPrompt: '您是否曾经被诊断过深静脉血栓（DVT）？',
      inputType: 'boolean',
      scoreWhenTrue: 1,
      scoreWhenFalse: 0,
    },
    {
      id: 'wells-dvt.alternative',
      clinicalLabel: '临床判断为其他诊断的可能性≥DVT',
      patientPrompt: '医生是否认为其他疾病的可能性至少与 DVT 相当？',
      helpText: '此项为临床判断，通常由医生评估。',
      inputType: 'boolean',
      scoreWhenTrue: -2,
      scoreWhenFalse: 0,
      requiresClinician: true,
    },
  ],
  tiers: [
    {
      id: 'low',
      label: '低概率',
      maxScore: 0,
      patientSummary: 'DVT 验前概率较低（文献发生率约 5%）。仍请结合医生意见决定是否进一步检查。',
      clinicianNote: '≤0 分：低概率',
      actionHint: '建议就医，由医生决定是否需要 D-二聚体或超声检查。',
    },
    {
      id: 'moderate',
      label: '中概率',
      minScore: 1,
      maxScore: 2,
      patientSummary: 'DVT 验前概率中等（文献发生率约 17%）。需要进一步检查。',
      clinicianNote: '1–2 分：中概率',
      actionHint: '请尽快就医，完善 D-二聚体或下肢静脉超声等检查。',
    },
    {
      id: 'high',
      label: '高概率',
      minScore: 3,
      patientSummary: 'DVT 验前概率较高（文献发生率约 53–75%）。请尽快就医评估。',
      clinicianNote: '≥3 分：高概率',
      actionHint: '请尽快就医，可能需要紧急影像或抗凝评估。',
    },
  ],
});
